import Image from "next/image";
import Hero from "@/components/Hero.jsx";
import Madam from "@/assets/comps/Madam.svg";
import Hi from "@/assets/comps/Hi.svg";
import download from "@/assets/comps/download.svg";


import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UNO-BiDirectional Translation Next App",
  description: "Generated by create next app",
};


export default function Home() {
  return (
    <div className="flex flex-col min-h-screen mx-auto px-4 pt-8 pb-16">
      <div className="flex-grow">
        <Head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
        </Head>
        <Navbar />
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="mb-16">
            <Hero />
          </div>
          <div className="grid grid-cols-2 gap-72">
            <div className="card w-96 bg-customBrown shadow-xl">
              <div className="card-body items-center text-center">
                <h2 className="card-title font-thin text-customGreen">
                  Different Languages
                </h2>
                <h3 className="font-bold text-customGreen">
                  Common Communication
                </h3>
                <Image src={Madam} alt = "Image" width={512} height={512} />
              </div>
            </div>
            <div className="card w-96 bg-customBrown shadow-xl">
              <div className="card-body items-center text-center">
                <h2 className="card-title font-thin text-customGreen">
                  Translate
                </h2>
                <h3 className="font-bold text-customGreen">
                  Anytime, Anywhere
                </h3>
                <Image src={Hi} alt = "Image" width={256} height={256} />
              </div>
            </div>
          </div>
          <div className="mx-auto">
            <div className="mt-7 grid gap-3 w-full sm:inline-flex">
              <a
                href="/translate"
                className="py-3 px-4 inline-flex justify-center items-center gap-x-2 text-sm font-semibold rounded-3xl border border-transparent bg-customDarkGreen text-black hover:bg- disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1"
              >
                Translate Now
              </a>
              <a
                className="py-3 px-4 inline-flex justify-center items-center gap-x-2 text-sm font-medium rounded-3xl border border-gray-200 bg-customGreen text-gray-800 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:pointer-events-none dark:focus:outline-none dark:focus:ring-1"
                href="#"
              >
                Download Extension
                <Image src={download} alt = "Download Icon" width={32} height={32} />
              </a>
            </div>
          </div>
        </main>
      </div>
      <Footer />
    </div>
  );
}
